name: Publish Preview
on: [pull_request]

jobs:
  publish-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: 'bun install'
      - run: '(cd playground && bun install)'
      - run: 'bun run dev:prepare'
      - run: 'bun run prepack'
      - run: 'bunx dlx pkg-pr-new publish'