name: Publish package
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
      - run: 'sed -i "s/\"version\": \".*\"/\"version\": \"${GITHUB_EVENT_RELEASE_TAG_NAME}\"/" package.json'
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      - run: 'bun install'
      - run: '(cd playground && bun install)'
      - run: 'bun run dev:prepare'
      - run: 'bun run prepack'
      - run: 'npm publish --provenance --access public'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
