name: 'Test package'
on: ['pull_request']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: 'bun install'
      - run: '(cd playground && bun install)'
      - run: 'bun run dev:prepare'
      - run: 'bun run eslint .'

  test-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: 'bun install'
      - run: '(cd playground && bun install)'
      - run: 'bun run dev:prepare'
      - run: 'bun run test:types'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: 'bun install'
      - run: '(cd playground && bun install)'
      - run: 'bun run dev:prepare'
      - run: 'bun run prepack'
